title: Juice-shop
description: An intentionally insecure webapp suitable for pentesting and security awareness trainings written in Node, Express and Angular.
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
